# serverless.yml


service: my-express-application


provider:

  name: aws

  stage: dev

  region: us-east-1

  profile: default


functions:

  app:

    handler: index.handler

    events:

      - http: ANY /

      - http: 'ANY {proxy+}'
