# serverless.yml


service: my-express-application

plugins:
  - serverless-offline


provider:

  name: aws

  stage: dev

  region: us-east-1

  profile: default


functions:

  app:

    handler: index.handler

    events:

      - http:
          path: /
          method: any
      - http:
          path: /*
          method: any
